config/routes.rb
Yapp::Application.routes.draw do

  resources :contributors

  resources :interviewees

  get "about" => "internal#about"

  get "contact" => "internal#contact"

  get "feedback" => "internal#feedback"

  mount Contenteditable::Engine => '/contenteditable'

  devise_for :users

  resources :users

  resources :categories

  resources :blocks

  resources :videos

  get "list" => "videos#list"

  get "home/index"

  get "home/video"

  get "login" => "home#login"

  match "add_category/:category_id/:object_type/:object_id" => "categories#add_category"
  match "delete_category/:category_id/:object_type/:object_id" => "categories#delete_category"

  get "c/:slug" => "categories#show"
  get ":slug" => "videos#show"

  root :to => 'home#index'

end

app/models/interviewee.rb
class Interviewee < ActiveRecord::Base
  attr_accessible :description, :pic, :title, :pic_cache
  mount_uploader :pic, PicUploader
  has_many :videos

end

app/controllers/interviewees_controller.rb
class IntervieweesController < ApplicationController
  # GET /interviewees
  # GET /interviewees.json
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @interviewees = Interviewee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interviewees }
    end
  end

  # GET /interviewees/1
  # GET /interviewees/1.json
  def show
    @interviewee = Interviewee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interviewee }
    end
  end

  # GET /interviewees/new
  # GET /interviewees/new.json
  def new
    @interviewee = Interviewee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interviewee }
    end
  end

  # GET /interviewees/1/edit
  def edit
    @interviewee = Interviewee.find(params[:id])
  end

  # POST /interviewees
  # POST /interviewees.json
  def create
    @interviewee = Interviewee.new(params[:interviewee])

    respond_to do |format|
      if @interviewee.save
        format.html { redirect_to @interviewee, notice: 'Interviewee was successfully created.' }
        format.json { render json: @interviewee, status: :created, location: @interviewee }
      else
        format.html { render action: "new" }
        format.json { render json: @interviewee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interviewees/1
  # PUT /interviewees/1.json
  def update
    @interviewee = Interviewee.find(params[:id])

    respond_to do |format|
      if @interviewee.update_attributes(params[:interviewee])
        format.html { redirect_to @interviewee, notice: 'Interviewee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interviewee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviewees/1
  # DELETE /interviewees/1.json
  def destroy
    @interviewee = Interviewee.find(params[:id])
    @interviewee.destroy

    respond_to do |format|
      format.html { redirect_to interviewees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/interviewees_helper.rb
module IntervieweesHelper
end

app/views/interviewees/_form.html.haml
= form_for @interviewee, :html => {:multipart => true} do |f|
  - if @interviewee.errors.any?
    #error_explanation
      %h2= "#{pluralize(@interviewee.errors.count, "error")} prohibited this interviewee from being saved:"
      %ul
        - @interviewee.errors.full_messages.each do |msg|
          %li= msg



  .field
    =f.label :pic
    = image_tag(@interviewee.pic_url) if @interviewee.pic?
    = f.file_field :pic
    = f.hidden_field :pic_cache

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/interviewees/edit.html.haml
%h1 Editing interviewee

= render 'form'

= link_to 'Show', @interviewee
\|
= link_to 'Back', interviewees_path

app/views/interviewees/index.html.haml
%h1 Listing interviewees

%table
  %tr
    %th Title
    %th Description
    %th Pic
    %th
    %th
    %th

  - @interviewees.each do |interviewee|
    %tr
      %td= interviewee.title
      %td= interviewee.description
      %td= image_tag interviewee.pic_url(:small_bw) if interviewee.pic?
      %td= link_to 'Show', interviewee
      %td= link_to 'Edit', edit_interviewee_path(interviewee)
      %td= link_to 'Destroy', interviewee, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Interviewee', new_interviewee_path

app/views/interviewees/new.html.haml
%h1 New interviewee

= render 'form'

= link_to 'Back', interviewees_path

app/views/interviewees/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @interviewee.title
%p
  %b Description:
  = @interviewee.description
%p
  %b Pic:
  = @interviewee.pic

= link_to 'Edit', edit_interviewee_path(@interviewee)
\|
= link_to 'Back', interviewees_path