config/routes.rb
Yapp::Application.routes.draw do

  resources :contributors

  resources :interviewees

  get "about" => "internal#about"

  get "contact" => "internal#contact"

  get "feedback" => "internal#feedback"

  mount Contenteditable::Engine => '/contenteditable'

  devise_for :users

  resources :users

  resources :categories

  resources :blocks

  resources :videos

  get "list" => "videos#list"

  get "home/index"

  get "home/video"

  get "login" => "home#login"

  match "add_category/:category_id/:object_type/:object_id" => "categories#add_category"
  match "delete_category/:category_id/:object_type/:object_id" => "categories#delete_category"

  get "c/:slug" => "categories#show"
  get ":slug" => "videos#show"

  root :to => 'home#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :interviewee_id, :title, :youtube, :description, :img, :img_cache, :slug
  mount_uploader :img, ImgUploader

  has_many :blocks
  has_many :category_relations, :as => :categoryable
  has_many :categories, :through => :category_relations
  belongs_to :interviewee

  before_save :generate_slug

  def generate_slug
    if self.slug.blank?
      slug = "#{self.title}"
      slug = Translit.convert(slug, :english)
      slug.gsub! /['`]/,""
      slug.gsub! /\s*@\s*/, " at "
      slug.gsub! /\s*&\s*/, " and "
      slug.gsub! /\s*[^A-Za-z0-9\.\-]\s*/, '_'
      slug.gsub! /_+/,"_"
      slug.gsub! /\A[_\.]+|[_\.]+\z/,""
      slug.downcase!
      self.slug = slug
    end
  end

  def url
    "/" + self.slug.to_s
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  before_filter :authenticate_user!, :except => [:index, :show]

  def list

    @blocks = Block.all.order(:start_time)

    @blocks_json = @blocks.map do |b|
      e = {}
      e[:start_time] = b.start_time
      e[:end_time] = b.end_time
      e[:answer_start] = b.answer_start
      e[:title] = b.title
      e[:youtube] = b.video.youtube
      e[:video_title] = b.video.title
      e[:video_description] = b.video.description
      e[:id] = b.id
      e
    end.to_json


    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @blocks }
    end

  end

  def index
    @videos = admin? ? Video.all : Video.where(:published => true).order("featured DESC")

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    slug = params[:slug]

    @video = Video.find(params[:id]) if slug.blank?
    @video = Video.find_by_slug(slug) if slug.present?

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
= form_for @video, :html => {:multipart => true} do |f|
  -if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg


  .field
    =f.label :img
    = image_tag(@video.img_url) if @video.img?
    = f.file_field :img
    = f.hidden_field :img_cache

  .field
    = f.label :youtube
    = f.text_field :youtube
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :interviewee_id
    = f.number_field :interviewee_id
  .actions
    = f.submit 'Save'

app/views/videos/_related.html.haml
%h1=caption
-videos.each do |video|
  .video-wrap
    =link_to(video.url, :class => 'video-image') do
      =image_tag("http://img.youtube.com/vi/#{video.youtube}/mqdefault.jpg")
      .long_button
        Смотреть
  %h3=video.title

app/views/videos/_search.html.haml
.videos
  -videos.each do |v|
    .a_video
      .video-wrap
        =link_to v.url, :class => 'video-image' do
          -if v.img?
            =image_tag v.img_url(:small)
          -else
            =image_tag("http://img.youtube.com/vi/#{v.youtube}/mqdefault.jpg")
          .long_button
            Смотреть

      %h3=v.title
      %p=v.description

app/views/videos/_videos.html.haml
%h1=caption
.row
  -videos.each do |video|
    .four.columns
      .video-wrap
        =link_to video.url, :class => 'video-image' do
          -if video.img?
            =image_tag video.img_url(:small)
          -else
            =image_tag("http://img.youtube.com/vi/#{video.youtube}/mqdefault.jpg")
          .long_button
            Смотреть
      %h3=video.title

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
.middle.top_padding.main-page


  -if admin?
    .internal_content.videos_page
      %h1 Все видео
      %h2
        =link_to 'Logout', destroy_user_session_path, :method => :delete

      - @videos.each do |video|
        .panel
          .row
            .three.columns
              .title
                %h2=link_to video.title, video
              .image
                =link_to image_tag("http://img.youtube.com/vi/#{video.youtube}/default.jpg"), video
            .three.columns
              .action.top_padding
                =link_to 'Show', video, :class => 'long_button'
              .info.top_padding
                Info:
                = video.youtube
              = link_to 'Edit', edit_video_path(video)
              = link_to 'Destroy', video, :confirm => 'Are you sure?', :method => :delete
            .six.columns
              .image
                =image_tag video.img_url(:small) if video.img?
          .description
            %h4=video.description
          .categories
            =render :partial => "categories/choose", :locals => {:object => video}
      = link_to 'Add New Video', new_video_path, :class => 'long_button'
  -else
    .the_content
      %h1 Все видео
      =render :partial => "videos/search", :locals => {:videos => @videos}

app/views/videos/list.html.haml
.middle.top_padding.video_page
  .the_content
    .video.flex-video.widescreen
      .progress-bar
        .the-progress
      .layer
      #video=1
    #notice= notice
    .row
      .eight.columns
        %h1.video_title
          = @blocks.first.video.title
        %p.video_description
          = @blocks.first.video.description
      .four.columns
        =render "social_media/like_buttons"
    .row
      .eight.columns
        %h1 Leave your comment
        =render 'social_media/facebook_comments'
      .four.columns
        =render :partial => "videos/related", :locals => {:videos => popular, :caption => "Related Videos"}



    .panel
      .current_time
        Current time
      .duration
        Duration
  .footer2
    Subscribe

.right_panel.top_padding
  =render :partial => "blocks/content", :locals => {:blocks => @blocks}
  .the_content.top_big_padding
    %h4.very-light Our partners
    =render "shared/partners"



-if 1 == 2
  .block_link.button{'data-start' => '50', 'data-end' => '100', 'data-video' => 'qlEsPBy4K48'} Example of link to external video (will play Steve Blank from 50 second)





:javascript
  loadPlaylist(#{@blocks_json});

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.haml
.middle.top_padding.video_page
  .the_content
    .video.flex-video.widescreen
      -#.progress-bar
        .the-progress
      -#.layer
      #video{'data-video' => @video.youtube}
        -if request.env['HTTP_USER_AGENT'].downcase.match(/android|iphone|ipad/)
          %iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "http://www.youtube.com/embed/#{@video.youtube}", :width => "560"}
          :css
            .right_panel {
              display:none !important;
            }
            html body .middle, html body .video_page .footer2 {
              //width: 70% !important;
              width: 100% !important;
              max-width:10000px;
            }
            body .no_flash_message {
              display:block;
            }

    .alert-box.success.no_flash_message
      Для полной функциональности, смотрите полную версию СтартапСтори с компьютера
    -if admin?
      Current time:
      %span.current_time
    #notice= notice
    .row
      .eight.columns
        %h1
          = @video.title
        %p
          = @video.description
      .four.columns
        =render :partial => "social_media/like_buttons", :locals => {:url => "http://startupstory.ru#{@video.url}/"}
    .row
      .eight.columns
        %h1 Leave your comment
        =render 'social_media/facebook_comments'
      .four.columns
        =render :partial => "videos/related", :locals => {:videos => popular, :caption => "Related Videos"}



  =render "layouts/footer"


.right_panel.top_padding
  =render :partial => 'blocks/right_panel', :locals => {:video => @video}
  .the_content.top_big_padding
    %h4.very-light Our partners
    =render "shared/partners"







-if 1 == 2
  .block_link.button{'data-start' => '50', 'data-end' => '100', 'data-video' => 'qlEsPBy4K48'} Example of link to external video (will play Steve Blank from 50 second)
  = link_to 'Edit', edit_video_path(@video)
  \|
  = link_to 'Back', videos_path

-provide :meta do
  %meta{:content => "StartupStory.Ru - #{@video.title}", :property => "og:title"}/
  %meta{:content => "website", :property => "og:type"}/
  %meta{:content => "http://startupstory.ru#{@video.url}/", :property => "og:url"}/
  %meta{:content => "http://img.youtube.com/vi/#{@video.youtube}/mqdefault.jpg", :property => "og:image"}/
  %meta{:content => "StartupStory.Ru", :property => "og:site_name"}/
  %meta{:content => "100000245725293", :property => "fb:admins"}/
  %meta{:content => "286819084665868", :property => "fb:app_id"}/
  %meta{:content => "Видеоинтервью с CEO стартапов из Кремниевой долины - #{@video.description}", :property => "og:description"}/