config/routes.rb
Yapp::Application.routes.draw do

  resources :contributors

  resources :interviewees

  get "about" => "internal#about"

  get "contact" => "internal#contact"

  get "feedback" => "internal#feedback"

  mount Contenteditable::Engine => '/contenteditable'

  devise_for :users

  resources :users

  resources :categories

  resources :blocks

  resources :videos

  get "list" => "videos#list"

  get "home/index"

  get "home/video"

  get "login" => "home#login"

  match "add_category/:category_id/:object_type/:object_id" => "categories#add_category"
  match "delete_category/:category_id/:object_type/:object_id" => "categories#delete_category"

  get "c/:slug" => "categories#show"
  get ":slug" => "videos#show"

  root :to => 'home#index'

end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
  attr_accessible :description, :pic, :title, :pic_cache
  mount_uploader :pic, PicUploader

end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  # GET /contributors
  # GET /contributors.json
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @contributors = Contributor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contributors }
    end
  end

  # GET /contributors/1
  # GET /contributors/1.json
  def show
    @contributor = Contributor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contributor }
    end
  end

  # GET /contributors/new
  # GET /contributors/new.json
  def new
    @contributor = Contributor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contributor }
    end
  end

  # GET /contributors/1/edit
  def edit
    @contributor = Contributor.find(params[:id])
  end

  # POST /contributors
  # POST /contributors.json
  def create
    @contributor = Contributor.new(params[:contributor])

    respond_to do |format|
      if @contributor.save
        format.html { redirect_to @contributor, notice: 'Contributor was successfully created.' }
        format.json { render json: @contributor, status: :created, location: @contributor }
      else
        format.html { render action: "new" }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contributors/1
  # PUT /contributors/1.json
  def update
    @contributor = Contributor.find(params[:id])

    respond_to do |format|
      if @contributor.update_attributes(params[:contributor])
        format.html { redirect_to @contributor, notice: 'Contributor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributors/1
  # DELETE /contributors/1.json
  def destroy
    @contributor = Contributor.find(params[:id])
    @contributor.destroy

    respond_to do |format|
      format.html { redirect_to contributors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/views/contributors/_form.html.haml
= form_for @contributor, :html => {:multipart => true} do |f|
  - if @contributor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contributor.errors.count, "error")} prohibited this contributor from being saved:"
      %ul
        - @contributor.errors.full_messages.each do |msg|
          %li= msg

  .field
    =f.label :pic
    = image_tag(@contributor.pic_url) if @contributor.pic?
    = f.file_field :pic
    = f.hidden_field :pic_cache

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :pic
    = f.text_field :pic
  .actions
    = f.submit 'Save'

app/views/contributors/edit.html.haml
%h1 Editing contributor

= render 'form'

= link_to 'Show', @contributor
\|
= link_to 'Back', contributors_path

app/views/contributors/index.html.haml
%h1 Listing contributors

%table
  %tr
    %th Title
    %th Description
    %th Pic
    %th
    %th
    %th

  - @contributors.each do |contributor|
    %tr
      %td= contributor.title
      %td= contributor.description
      %td= contributor.pic
      %td= link_to 'Show', contributor
      %td= link_to 'Edit', edit_contributor_path(contributor)
      %td= link_to 'Destroy', contributor, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Contributor', new_contributor_path

app/views/contributors/new.html.haml
%h1 New contributor

= render 'form'

= link_to 'Back', contributors_path

app/views/contributors/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @contributor.title
%p
  %b Description:
  = @contributor.description
%p
  %b Pic:
  = @contributor.pic

= link_to 'Edit', edit_contributor_path(@contributor)
\|
= link_to 'Back', contributors_path